### ISSUE TITLE
the current release lacks the actual files needed to import it

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [seandst/diaper#3]

**Comment by RonnyPfannschmidt** [comment]
the actual detail issue is that setup.cfg was used incorrectly

also if possible avoid pbr, outside of openstack its just a massive broken pain

**Comment by tehsmyers** [comment]
Looks like it was just the wheel, so I pulled that from pypi. The pbr opinions are unwelcome: critical opinions without constructive options are useless, keep them to yourself.
