### ISSUE TITLE
tarball won't install the python file

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [seandst/diaper#4]
```
$ virtualenv diaper-env && diaper-env/bin/pip install diaper --no-binary diaper && ls diaper-env/lib/python2.7/site-packages/
New python executable in /home/rpfannsc/diaper-env/bin/python2
Not overwriting existing python script /home/rpfannsc/diaper-env/bin/python (you must use /home/rpfannsc/diaper-env/bin/python2)
Installing setuptools, pip, wheel...done.
Collecting diaper
  Using cached diaper-1.4.0.tar.gz
Skipping bdist_wheel for diaper, due to binaries being disabled for it.
Installing collected packages: diaper
  Running setup.py install for diaper ... done
Successfully installed diaper-1.4.0
diaper-1.4.0-py2.7.egg-info  easy_install.py  easy_install.pyc  pip  pip-9.0.3.dist-info  pkg_resources  setuptools  setuptools-39.0.1.dist-info  wheel  wheel-0.30.0.dist-info
```

btw, same happens with skipping the binary, in which case a broken wheel is made first (because the setup.cfg is wrong as i told in #3 )

additionally the setup-requirement on pbr broke builds on rtd

**Comment by tehsmyers** [comment]
So, again, you're telling me setup.cfg is wrong, but not anything about how it's wrong. That is entirely useless.

**Comment by RonnyPfannschmidt** [comment]
my guess would be that you declared a package where you have a module, but in the end this is pbr, you picked it, you go figure how it works correctly, and btw, if you don't publish wheels there is a good chance it will break peoples builds ^^ (like on readthedocs where pbr just crashes the install process)

**Comment by tehsmyers** [comment]
Well, thanks for your guess, I guess?
